import { PrismaClient, UserRole } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting to seed dummy data...\n');

  // 1. Create School Users and Profiles
  console.log('📚 Creating schools...');
  const schools = [
    {
      name: 'Seoul International Academy',
      email: 'contact@seoul-academy.edu',
      country: 'South Korea',
      city: 'Seoul',
      schoolType: 'International School',
      description: 'Seoul International Academy is a leading international school offering the IB curriculum to students from Pre-K through Grade 12. Our mission is to provide a world-class education that prepares students for success in an increasingly global society.',
      website: 'https://seoul-academy.edu',
      isVerified: true,
    },
    {
      name: 'Dubai English Speaking School',
      email: 'info@dubai-ess.ae',
      country: 'United Arab Emirates',
      city: 'Dubai',
      schoolType: 'Private School',
      description: 'Premier British curriculum school in the heart of Dubai, offering world-class education with state-of-the-art facilities and experienced international faculty.',
      website: 'https://dubai-ess.ae',
      isVerified: true,
    },
    {
      name: 'Shanghai American School',
      email: 'admissions@sas.edu.cn',
      country: 'China',
      city: 'Shanghai',
      schoolType: 'International School',
      description: 'One of the largest and most established international schools in China, providing American curriculum education to expatriate and Chinese national students.',
      website: 'https://sas.edu.cn',
      isVerified: true,
    },
    {
      name: 'Bangkok British School',
      email: 'hello@bangkok-british.ac.th',
      country: 'Thailand',
      city: 'Bangkok',
      schoolType: 'British Curriculum',
      description: 'Following the National Curriculum for England, we provide outstanding British education in the heart of Bangkok with a diverse international community.',
      website: 'https://bangkok-british.ac.th',
      isVerified: true,
    },
    {
      name: 'Tokyo International School',
      email: 'admissions@tis.ac.jp',
      country: 'Japan',
      city: 'Tokyo',
      schoolType: 'International School',
      description: 'A vibrant international learning community in Tokyo, offering IB programs and fostering global citizenship among students from over 50 countries.',
      website: 'https://tis.ac.jp',
      isVerified: true,
    },
    {
      name: 'Singapore International Academy',
      email: 'info@sia.edu.sg',
      country: 'Singapore',
      city: 'Singapore',
      schoolType: 'IB Curriculum',
      description: 'Providing exceptional IB education with a focus on holistic development, academic excellence, and preparing students for global universities.',
      website: 'https://sia.edu.sg',
      isVerified: true,
    },
    {
      name: 'Hanoi International School',
      email: 'admissions@his.edu.vn',
      country: 'Vietnam',
      city: 'Hanoi',
      schoolType: 'International School',
      description: 'Leading international school in Vietnam offering American curriculum with a multicultural environment and excellent facilities.',
      website: 'https://his.edu.vn',
      isVerified: true,
    },
    {
      name: 'Kuala Lumpur International School',
      email: 'info@klis.edu.my',
      country: 'Malaysia',
      city: 'Kuala Lumpur',
      schoolType: 'International School',
      description: 'Established international school providing high-quality education in the heart of KL with modern facilities and experienced teachers.',
      website: 'https://klis.edu.my',
      isVerified: true,
    },
  ];

  const createdSchools = [];
  for (const school of schools) {
    const hashedPassword = await bcrypt.hash('School123!@#', 10);

    const user = await prisma.user.create({
      data: {
        email: school.email,
        password: hashedPassword,
        name: school.name,
        role: UserRole.SCHOOL,
        emailVerified: new Date(),
        status: 'ACTIVE',
      },
    });

    const schoolProfile = await prisma.schoolProfile.create({
      data: {
        userId: user.id,
        schoolName: school.name,
        country: school.country,
        city: school.city,
        schoolType: school.schoolType,
        description: school.description,
        website: school.website,
        isVerified: school.isVerified,
        verifiedAt: new Date(),
      },
    });

    createdSchools.push({ user, profile: schoolProfile, ...school });
    console.log(`  ✓ Created ${school.name}`);
  }

  // 2. Create Recruiter Users and Profiles
  console.log('\n🔍 Creating recruiters...');
  const recruiters = [
    {
      name: 'Global Teaching Recruiters',
      email: 'contact@globalteachrecruit.com',
      companyName: 'Global Teaching Recruiters Ltd.',
      country: 'United Kingdom',
    },
    {
      name: 'Asia Education Partners',
      email: 'info@asiaedupartners.com',
      companyName: 'Asia Education Partners Inc.',
      country: 'Singapore',
    },
  ];

  const createdRecruiters = [];
  for (const recruiter of recruiters) {
    const hashedPassword = await bcrypt.hash('Recruiter123!@#', 10);

    const user = await prisma.user.create({
      data: {
        email: recruiter.email,
        password: hashedPassword,
        name: recruiter.name,
        role: UserRole.RECRUITER,
        emailVerified: new Date(),
        status: 'ACTIVE',
      },
    });

    const recruiterProfile = await prisma.recruiterProfile.create({
      data: {
        userId: user.id,
        companyName: recruiter.companyName,
        country: recruiter.country,
        isVerified: true,
        verifiedAt: new Date(),
      },
    });

    createdRecruiters.push({ user, profile: recruiterProfile });
    console.log(`  ✓ Created ${recruiter.name}`);
  }

  // 3. Create Job Postings
  console.log('\n💼 Creating job postings...');
  const jobs = [
    // Seoul International Academy
    {
      schoolId: createdSchools[0].profile.id,
      title: 'ESL Teacher',
      description: 'We are seeking an enthusiastic ESL teacher to join our elementary department. The ideal candidate will have experience teaching young learners and creating engaging, student-centered lessons. You will work with small class sizes in a supportive, collaborative environment.',
      subject: 'English',
      country: 'South Korea',
      city: 'Seoul',
      schoolName: createdSchools[0].name,
      minYearsExperience: 2,
      requiredSubjects: ['English', 'ESL'],
      requirements: 'Bachelor degree in Education or related field, TEFL/TESOL certificate, 2+ years teaching experience',
      salaryUSD: 2800,
      benefits: 'Housing allowance, health insurance, flight reimbursement, pension contribution',
      housingProvided: true,
      flightProvided: true,
      contractLength: 12,
      startDate: new Date('2025-08-15'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor degree required, Master preferred',
      experienceRequirements: '2+ years of ESL teaching experience',
      status: 'ACTIVE',
    },
    {
      schoolId: createdSchools[0].profile.id,
      title: 'Mathematics Teacher - Middle School',
      description: 'Join our mathematics department to teach grades 6-8. We are looking for a creative and passionate teacher who can inspire students to love mathematics through innovative teaching methods and real-world applications.',
      subject: 'Mathematics',
      country: 'South Korea',
      city: 'Seoul',
      schoolName: createdSchools[0].name,
      minYearsExperience: 3,
      requiredSubjects: ['Mathematics'],
      requirements: 'Bachelor or Master degree in Mathematics or Education, qualified teacher status',
      salaryUSD: 3500,
      benefits: 'Furnished housing, health insurance, annual flight home, professional development budget',
      housingProvided: true,
      flightProvided: true,
      contractLength: 24,
      startDate: new Date('2025-09-01'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor degree required, Master preferred',
      experienceRequirements: '3+ years teaching mathematics at middle school level',
      status: 'ACTIVE',
    },
    // Dubai English Speaking School
    {
      schoolId: createdSchools[1].profile.id,
      title: 'Primary School Teacher',
      description: 'Excellent opportunity for an experienced primary teacher to join our outstanding school. You will be responsible for teaching all subjects to a class of 20-25 students, following the British National Curriculum.',
      subject: 'General',
      country: 'United Arab Emirates',
      city: 'Dubai',
      schoolName: createdSchools[1].name,
      minYearsExperience: 3,
      requiredSubjects: ['General', 'English', 'Mathematics', 'Science'],
      requirements: 'UK QTS or equivalent, experience with British curriculum, strong classroom management',
      salaryUSD: 4500,
      currency: 'USD',
      benefits: 'Tax-free salary, furnished accommodation, health insurance, annual flights, end-of-service gratuity',
      housingProvided: true,
      flightProvided: true,
      contractLength: 24,
      startDate: new Date('2025-08-20'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor in Education, QTS required',
      experienceRequirements: 'Minimum 3 years primary teaching experience',
      status: 'ACTIVE',
    },
    {
      schoolId: createdSchools[1].profile.id,
      title: 'Science Teacher - Secondary',
      description: 'We need a passionate science teacher for our secondary department. The role involves teaching Biology, Chemistry, and Physics to students aged 11-16 preparing for IGCSE examinations.',
      subject: 'Science',
      country: 'United Arab Emirates',
      city: 'Dubai',
      schoolName: createdSchools[1].name,
      minYearsExperience: 4,
      requiredSubjects: ['Science', 'Biology', 'Chemistry', 'Physics'],
      requirements: 'Science degree, teaching qualification, IGCSE experience preferred',
      salaryUSD: 5000,
      benefits: 'Tax-free salary, housing, medical insurance, annual return flights, tuition discount for children',
      housingProvided: true,
      flightProvided: true,
      contractLength: 24,
      startDate: new Date('2025-09-05'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor in Science, teaching qualification',
      experienceRequirements: '4+ years secondary science teaching',
      status: 'ACTIVE',
    },
    // Shanghai American School
    {
      schoolId: createdSchools[2].profile.id,
      title: 'High School English Teacher',
      description: 'Teach English Language Arts to high school students in our well-established American curriculum program. Small class sizes and excellent resources available.',
      subject: 'English',
      country: 'China',
      city: 'Shanghai',
      schoolName: createdSchools[2].name,
      minYearsExperience: 5,
      requiredSubjects: ['English', 'Literature'],
      requirements: 'State teaching license, Bachelor degree minimum, high school teaching experience',
      salaryUSD: 4200,
      benefits: 'Furnished housing, comprehensive health coverage, relocation allowance, professional development',
      housingProvided: true,
      flightProvided: true,
      contractLength: 24,
      startDate: new Date('2025-08-10'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor required, Master preferred',
      experienceRequirements: '5+ years high school English teaching',
      status: 'ACTIVE',
    },
    {
      schoolId: createdSchools[2].profile.id,
      title: 'Physical Education Teacher',
      description: 'Dynamic PE teacher needed to lead our athletics program. Responsibilities include teaching PE classes, coaching sports teams, and organizing school-wide sporting events.',
      subject: 'Physical Education',
      country: 'China',
      city: 'Shanghai',
      schoolName: createdSchools[2].name,
      minYearsExperience: 2,
      requiredSubjects: ['Physical Education', 'Sports'],
      requirements: 'PE teaching qualification, coaching experience, first aid certified',
      salaryUSD: 3800,
      benefits: 'Housing, health insurance, flights, gym membership',
      housingProvided: true,
      flightProvided: true,
      contractLength: 12,
      startDate: new Date('2025-08-15'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor in Physical Education or related field',
      experienceRequirements: '2+ years PE teaching and coaching',
      status: 'ACTIVE',
    },
    // Bangkok British School
    {
      schoolId: createdSchools[3].profile.id,
      title: 'Early Years Teacher',
      description: 'We are looking for a caring and creative early years teacher for our Foundation Stage. Experience with the EYFS curriculum essential.',
      subject: 'Early Childhood',
      country: 'Thailand',
      city: 'Bangkok',
      schoolName: createdSchools[3].name,
      minYearsExperience: 2,
      requiredSubjects: ['Early Childhood Education'],
      requirements: 'Early Years qualification, EYFS experience, positive and nurturing approach',
      salaryUSD: 2600,
      benefits: 'Accommodation allowance, health insurance, annual flight, work permit and visa support',
      housingProvided: false,
      flightProvided: true,
      contractLength: 12,
      startDate: new Date('2025-08-01'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Early Childhood Education degree',
      experienceRequirements: '2+ years EYFS teaching',
      status: 'ACTIVE',
    },
    // Tokyo International School
    {
      schoolId: createdSchools[4].profile.id,
      title: 'IB Diploma Coordinator',
      description: 'Senior leadership role managing our IB Diploma Programme. Responsibilities include curriculum oversight, staff development, and ensuring programme standards.',
      subject: 'Administration',
      country: 'Japan',
      city: 'Tokyo',
      schoolName: createdSchools[4].name,
      minYearsExperience: 7,
      requiredSubjects: ['IB', 'Administration'],
      requirements: 'IB training, extensive teaching experience, leadership skills, Master degree preferred',
      salaryUSD: 5500,
      benefits: 'Housing stipend, comprehensive insurance, retirement plan, professional development, relocation support',
      housingProvided: false,
      flightProvided: true,
      contractLength: 24,
      startDate: new Date('2025-07-01'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Master degree in Education or related field',
      experienceRequirements: '7+ years teaching, 3+ years IB experience, leadership experience required',
      status: 'ACTIVE',
    },
    {
      schoolId: createdSchools[4].profile.id,
      title: 'Music Teacher',
      description: 'Passionate music educator needed to teach general music classes and lead instrumental programs. Experience with various instruments and musical styles valued.',
      subject: 'Music',
      country: 'Japan',
      city: 'Tokyo',
      schoolName: createdSchools[4].name,
      minYearsExperience: 3,
      requiredSubjects: ['Music'],
      requirements: 'Music degree, teaching qualification, proficiency in multiple instruments',
      salaryUSD: 3900,
      benefits: 'Housing allowance, health insurance, visa sponsorship, instrument access',
      housingProvided: false,
      flightProvided: true,
      contractLength: 12,
      startDate: new Date('2025-08-20'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor in Music or Music Education',
      experienceRequirements: '3+ years music teaching experience',
      status: 'ACTIVE',
    },
    // Singapore International Academy
    {
      schoolId: createdSchools[5].profile.id,
      title: 'IB Biology Teacher',
      description: 'Teach IB Biology at Standard and Higher Level. Join our science department and help students achieve excellence in their examinations.',
      subject: 'Biology',
      country: 'Singapore',
      city: 'Singapore',
      schoolName: createdSchools[5].name,
      minYearsExperience: 4,
      requiredSubjects: ['Biology', 'Science'],
      requirements: 'Biology degree, IB training or experience, teaching qualification',
      salaryUSD: 4800,
      benefits: 'Competitive salary, housing allowance, CPF contributions, medical insurance, professional development',
      housingProvided: false,
      flightProvided: true,
      contractLength: 24,
      startDate: new Date('2025-08-01'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor in Biology, Master preferred',
      experienceRequirements: '4+ years Biology teaching, IB experience required',
      status: 'ACTIVE',
    },
    {
      schoolId: createdSchools[5].profile.id,
      title: 'Learning Support Teacher',
      description: 'Support students with diverse learning needs across all grade levels. Work collaboratively with classroom teachers to implement differentiated instruction.',
      subject: 'Special Education',
      country: 'Singapore',
      city: 'Singapore',
      schoolName: createdSchools[5].name,
      minYearsExperience: 3,
      requiredSubjects: ['Special Education', 'Learning Support'],
      requirements: 'Special education qualification, experience with inclusive education, patience and empathy',
      salaryUSD: 4200,
      benefits: 'Competitive package, housing allowance, medical benefits, visa support, CPF',
      housingProvided: false,
      flightProvided: true,
      contractLength: 24,
      startDate: new Date('2025-08-15'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor in Special Education',
      experienceRequirements: '3+ years learning support experience',
      status: 'ACTIVE',
    },
    // Hanoi International School
    {
      schoolId: createdSchools[6].profile.id,
      title: 'Elementary Homeroom Teacher',
      description: 'Teach all subjects to elementary students in a diverse, multicultural environment. Small class sizes and collaborative team.',
      subject: 'General',
      country: 'Vietnam',
      city: 'Hanoi',
      schoolName: createdSchools[6].name,
      minYearsExperience: 2,
      requiredSubjects: ['General', 'Elementary Education'],
      requirements: 'Teaching license, elementary teaching experience, adaptable and culturally sensitive',
      salaryUSD: 2400,
      benefits: 'Furnished housing, health insurance, annual flights, visa support, settling-in allowance',
      housingProvided: true,
      flightProvided: true,
      contractLength: 12,
      startDate: new Date('2025-08-10'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor in Elementary Education',
      experienceRequirements: '2+ years elementary teaching',
      status: 'ACTIVE',
    },
    // Kuala Lumpur International School
    {
      schoolId: createdSchools[7].profile.id,
      title: 'Computer Science Teacher',
      description: 'Teach computer science and coding to middle and high school students. Experience with Python, Java, and web development preferred.',
      subject: 'Computer Science',
      country: 'Malaysia',
      city: 'Kuala Lumpur',
      schoolName: createdSchools[7].name,
      minYearsExperience: 3,
      requiredSubjects: ['Computer Science', 'Technology'],
      requirements: 'Computer Science degree, teaching qualification, programming expertise',
      salaryUSD: 3200,
      benefits: 'Housing allowance, medical insurance, annual flight, visa sponsorship, tech budget',
      housingProvided: false,
      flightProvided: true,
      contractLength: 12,
      startDate: new Date('2025-08-25'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor in Computer Science or related field',
      experienceRequirements: '3+ years teaching CS or related subjects',
      status: 'ACTIVE',
    },
    {
      schoolId: createdSchools[7].profile.id,
      title: 'Art Teacher',
      description: 'Creative and inspiring art teacher needed to develop our visual arts program across all grade levels.',
      subject: 'Art',
      country: 'Malaysia',
      city: 'Kuala Lumpur',
      schoolName: createdSchools[7].name,
      minYearsExperience: 2,
      requiredSubjects: ['Art', 'Visual Arts'],
      requirements: 'Art or Art Education degree, diverse art skills, portfolio of work',
      salaryUSD: 2900,
      benefits: 'Accommodation support, health coverage, flights, art supplies budget',
      housingProvided: false,
      flightProvided: true,
      contractLength: 12,
      startDate: new Date('2025-08-15'),
      employmentType: 'FULL_TIME',
      educationRequirements: 'Bachelor in Art or Art Education',
      experienceRequirements: '2+ years art teaching',
      status: 'ACTIVE',
    },
  ];

  const createdJobs = [];
  for (const job of jobs) {
    const createdJob = await prisma.jobPosting.create({
      data: job,
    });
    createdJobs.push(createdJob);
    console.log(`  ✓ Created ${job.title} at ${job.schoolName}`);
  }

  // 4. Create Teacher Users and Profiles
  console.log('\n👨‍🏫 Creating teacher profiles...');
  const teachers = [
    {
      email: 'john.smith@email.com',
      name: 'John Smith',
      firstName: 'John',
      lastName: 'Smith',
      bio: 'Experienced ESL teacher with a passion for helping students develop language skills through interactive and engaging lessons.',
      currentCountry: 'United States',
      preferredCountries: ['South Korea', 'Japan', 'China'],
      yearsExperience: 5,
      subjects: ['English', 'ESL'],
      degreeLevel: 'Bachelor',
      degreeMajor: 'English Literature',
      certifications: ['TEFL', 'TESOL'],
      hasTeachingLicense: true,
      hasTEFL: true,
      citizenship: 'United States',
      age: 32,
      minSalaryUSD: 2500,
      maxSalaryUSD: 3500,
    },
    {
      email: 'sarah.johnson@email.com',
      name: 'Sarah Johnson',
      firstName: 'Sarah',
      lastName: 'Johnson',
      bio: 'Mathematics specialist with 8 years of experience teaching middle and high school students. Committed to making math accessible and enjoyable.',
      currentCountry: 'Canada',
      preferredCountries: ['United Arab Emirates', 'Singapore', 'Qatar'],
      yearsExperience: 8,
      subjects: ['Mathematics', 'Algebra', 'Calculus'],
      degreeLevel: 'Master',
      degreeMajor: 'Mathematics Education',
      certifications: ['Ontario Teaching Certificate'],
      hasTeachingLicense: true,
      hasTEFL: false,
      citizenship: 'Canada',
      age: 35,
      minSalaryUSD: 4000,
      maxSalaryUSD: 5500,
    },
    {
      email: 'david.wong@email.com',
      name: 'David Wong',
      firstName: 'David',
      lastName: 'Wong',
      bio: 'Science educator passionate about hands-on learning and scientific inquiry. Experience with IB and IGCSE curricula.',
      currentCountry: 'Australia',
      preferredCountries: ['Singapore', 'Thailand', 'Vietnam'],
      yearsExperience: 6,
      subjects: ['Science', 'Biology', 'Chemistry'],
      degreeLevel: 'Master',
      degreeMajor: 'Biology',
      certifications: ['Queensland Teacher Registration'],
      hasTeachingLicense: true,
      hasTEFL: false,
      citizenship: 'Australia',
      age: 38,
      minSalaryUSD: 3500,
      maxSalaryUSD: 4800,
    },
    {
      email: 'emma.brown@email.com',
      name: 'Emma Brown',
      firstName: 'Emma',
      lastName: 'Brown',
      bio: 'Early years specialist with expertise in play-based learning and child development. Warm, nurturing teaching style.',
      currentCountry: 'United Kingdom',
      preferredCountries: ['United Arab Emirates', 'China', 'South Korea'],
      yearsExperience: 4,
      subjects: ['Early Childhood Education'],
      degreeLevel: 'Bachelor',
      degreeMajor: 'Early Childhood Education',
      certifications: ['EYFS Specialist', 'QTS'],
      hasTeachingLicense: true,
      hasTEFL: false,
      citizenship: 'United Kingdom',
      age: 29,
      minSalaryUSD: 2800,
      maxSalaryUSD: 4000,
    },
    {
      email: 'michael.chen@email.com',
      name: 'Michael Chen',
      firstName: 'Michael',
      lastName: 'Chen',
      bio: 'Technology enthusiast teaching computer science and coding. Building the next generation of programmers and problem solvers.',
      currentCountry: 'Singapore',
      preferredCountries: ['Japan', 'South Korea', 'Malaysia'],
      yearsExperience: 7,
      subjects: ['Computer Science', 'Technology', 'Coding'],
      degreeLevel: 'Master',
      degreeMajor: 'Computer Science',
      certifications: ['Google Certified Educator'],
      hasTeachingLicense: true,
      hasTEFL: false,
      citizenship: 'Singapore',
      age: 34,
      minSalaryUSD: 3800,
      maxSalaryUSD: 5000,
    },
    {
      email: 'lisa.garcia@email.com',
      name: 'Lisa Garcia',
      firstName: 'Lisa',
      lastName: 'Garcia',
      bio: 'Primary school generalist with a love for creating inclusive, student-centered classrooms where every child can thrive.',
      currentCountry: 'Spain',
      preferredCountries: ['United Arab Emirates', 'Qatar', 'Saudi Arabia'],
      yearsExperience: 10,
      subjects: ['General', 'English', 'Social Studies'],
      degreeLevel: 'Bachelor',
      degreeMajor: 'Elementary Education',
      certifications: ['Spanish Teaching License', 'Cambridge CELTA'],
      hasTeachingLicense: true,
      hasTEFL: true,
      citizenship: 'Spain',
      age: 36,
      minSalaryUSD: 3200,
      maxSalaryUSD: 4500,
    },
    {
      email: 'robert.anderson@email.com',
      name: 'Robert Anderson',
      firstName: 'Robert',
      lastName: 'Anderson',
      bio: 'Physical Education teacher and sports coach. Promoting healthy lifestyles and teamwork through athletics and movement education.',
      currentCountry: 'Ireland',
      preferredCountries: ['China', 'Thailand', 'Vietnam'],
      yearsExperience: 5,
      subjects: ['Physical Education', 'Health', 'Sports'],
      degreeLevel: 'Bachelor',
      degreeMajor: 'Physical Education',
      certifications: ['First Aid', 'Coaching Certification'],
      hasTeachingLicense: true,
      hasTEFL: false,
      citizenship: 'Ireland',
      age: 31,
      minSalaryUSD: 2600,
      maxSalaryUSD: 3800,
    },
    {
      email: 'maria.rodriguez@email.com',
      name: 'Maria Rodriguez',
      firstName: 'Maria',
      lastName: 'Rodriguez',
      bio: 'Bilingual educator teaching Spanish and English. Cultural ambassador fostering global awareness and language acquisition.',
      currentCountry: 'Mexico',
      preferredCountries: ['United Arab Emirates', 'Singapore', 'South Korea'],
      yearsExperience: 6,
      subjects: ['Spanish', 'English', 'ESL'],
      degreeLevel: 'Master',
      degreeMajor: 'Modern Languages',
      certifications: ['DELE', 'TESOL'],
      hasTeachingLicense: true,
      hasTEFL: true,
      citizenship: 'Mexico',
      age: 33,
      minSalaryUSD: 3000,
      maxSalaryUSD: 4200,
    },
  ];

  for (const teacher of teachers) {
    const hashedPassword = await bcrypt.hash('Teacher123!@#', 10);

    const user = await prisma.user.create({
      data: {
        email: teacher.email,
        password: hashedPassword,
        name: teacher.name,
        role: UserRole.TEACHER,
        emailVerified: new Date(),
        status: 'ACTIVE',
        profileCompleteness: 85,
      },
    });

    await prisma.teacherProfile.create({
      data: {
        userId: user.id,
        firstName: teacher.firstName,
        lastName: teacher.lastName,
        bio: teacher.bio,
        currentCountry: teacher.currentCountry,
        preferredCountries: teacher.preferredCountries,
        yearsExperience: teacher.yearsExperience,
        subjects: teacher.subjects,
        degreeLevel: teacher.degreeLevel,
        degreeMajor: teacher.degreeMajor,
        certifications: teacher.certifications,
        hasTeachingLicense: teacher.hasTeachingLicense,
        hasTEFL: teacher.hasTEFL,
        citizenship: teacher.citizenship,
        age: teacher.age,
        minSalaryUSD: teacher.minSalaryUSD,
        maxSalaryUSD: teacher.maxSalaryUSD,
        profileCompleteness: 85,
        status: 'ACTIVE',
      },
    });

    console.log(`  ✓ Created ${teacher.name}`);
  }

  console.log('\n✨ Dummy data seeding completed successfully!\n');
  console.log('📊 Summary:');
  console.log(`  - ${createdSchools.length} schools created`);
  console.log(`  - ${createdRecruiters.length} recruiters created`);
  console.log(`  - ${createdJobs.length} job postings created`);
  console.log(`  - ${teachers.length} teacher profiles created`);
  console.log('\n🔐 Test Credentials:');
  console.log('  Schools: contact@seoul-academy.edu / School123!@#');
  console.log('  Teachers: john.smith@email.com / Teacher123!@#');
  console.log('  Recruiters: contact@globalteachrecruit.com / Recruiter123!@#');
  console.log('  Admin: admin@aijobx.com / Admin123!@#\n');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding data:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
